Developing-a-Blog-Website-with-Django-main/bog_webite_django/App_Blog/urls.py
from django.urls import path
from App_Blog import views
from django.conf import settings
from django.conf.urls.static import static




app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
    path('delete/<pk>/', views.DeleteBlog.as_view(), name='delete_blog'),
 

    path('search/', views.BlogSearchView.as_view(), name='search_blog'),
    path('blog-most-liked/',views.MostLikedBlogView.as_view(),name='most_liked_blog'),
    path('blog-most-cmt/',views.MostCommentedBlogView.as_view(),name='most_commented_blog'),
    
    path('upload/',views.UploadVideo.as_view(), name='upload_video'),
    path('uploadlist/',views.UploadList.as_view(),name='upload_list'),
    # path('delete_video/<int:pk>/',views.DeleteVideo.as_view(), name='delete_video'),
   
]

Developing-a-Blog-Website-with-Django-main/bog_webite_django/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Developing-a-Blog-Website-with-Django-main/bog_webite_django/App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="What is on your mind?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date',]

    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-comment_date',)
        
    def __str__(self):
        return self.comment

class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="liked_blog")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="liker_user")


    def __str__(self):
        return self.user + " likes " + self.blog

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    tags = models.CharField(max_length=100)
    
class Video(models.Model): 
    caption=models.CharField(max_length=100)
    video=models.FileField(upload_to="video")

    def __str__(self):
        return self.caption

Developing-a-Blog-Website-with-Django-main/bog_webite_django/App_Blog/forms.py
from django import forms
from App_Blog.models import Blog, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

Developing-a-Blog-Website-with-Django-main/bog_webite_django/App_Blog/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView,DeleteView
from App_Blog.models import Blog, Comment, Likes,Video
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from App_Blog.forms import CommentForm
import uuid
from django.shortcuts import render,redirect, get_object_or_404
from django.core.paginator import Paginator
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from.models import Post
from django.db.models import Count
from django.contrib.auth.models import User
from .models import Video



# Create your views here.
# Create your views here.

class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'App_Blog/my_blogs.html'

# 1 view được sử dụng để hiển thị một mẫu cho người dùng tạo blog mới trong ứng dụng Django.
class CreateBlog(LoginRequiredMixin, CreateView):
    #Thuộc tính này chỉ định model mà view này sẽ sử dụng để tạo đối tượng. 
    model = Blog       

    #Điều này chỉ định tên của tệp mẫu mà view này sẽ sử dụng để hiển thị giao diện người dùng. 
    template_name = 'App_Blog/create_blog.html'

    #Đây là một tuple của các trường từ model Blog mà người dùng có thể nhập dữ liệu trong mẫu. 
    fields = ('blog_title', 'blog_content', 'blog_image',) 

    def form_valid(self, form):
        # Lưu đối tượng Blog từ dữ liệu mẫu, nhưng không commit vào cơ sở dữ liệu
        blog_obj = form.save(commit=False) 
        # Gán tác giả của bài đăng là người dùng hiện tại

        blog_obj.author = self.request.user
        #Lấy tiêu đề của blog từ mẫu
        title = blog_obj.blog_title
        #Tạo slug cho blog, thay thế khoảng trắng bằng "-" và thêm một UUID duy nhất
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        #Lưu đối tượng Blog vào cơ sở dữ liệu
        blog_obj.save()
        #Chuyển hướng người dùng về trang chính sau khi tạo blog thành công
        return HttpResponseRedirect(reverse('index'))
    
#
#   
#hiển thị một danh sách các bài đăng bằng cách sử dụng một mẫu được chỉ định
class BlogList(ListView):
    
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'
    context_object_name = 'blogs'
    paginate_by = 2

#
#
#
@login_required
def blog_details(request, slug):
    # # Lấy đối tượng Blog từ cơ sở dữ liệu dựa trên slug
    blog = Blog.objects.get(slug=slug)
    #Tạo một biểu mẫu mới cho phản hồi
    comment_form = CommentForm()
    # # Kiểm tra xem người dùng đã thích bài đăng này chưa
    already_liked = Likes.objects.filter(blog=blog, user= request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    # Xử lý khi người dùng gửi một phản hồi mới
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
    # Chuyển hướng người dùng trở lại trang chi tiết bài đăng sau khi gửi phản hồi
            return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':slug}))
    #Trả về trang chi tiết bài đăng với các thông tin cần thiết
    return render(request, 'App_Blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked,})
#
#
# xử lý hành động của người dùng khi họ thích một bài đăng cụ thể.
@login_required
def liked(request, pk):
        # Lấy đối tượng Blog từ cơ sở dữ liệu dựa trên khóa chính (primary key)
    blog = Blog.objects.get(pk=pk)
         # Lấy thông tin người dùng hiện tại
    user = request.user
         # Kiểm tra xem người dùng đã thích bài đăng này chưa
    already_liked = Likes.objects.filter(blog=blog, user=user)
         # Nếu người dùng chưa thích bài đăng này
    if not already_liked:
         # Tạo một bản ghi mới trong bảng Likes đại diện cho sự thích của người dùng đối với bài đăng này
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
         # Chuyển hướng người dùng trở lại trang chi tiết bài đăng sau khi họ thích bài đăng
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))
#
#
# thêm và xóa việc thích một bài đăng
@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))
# một view dựa trên lớp trong Django
class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'App_Blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Blog:blog_details', kwargs={'slug':self.object.slug})
    
class DeleteBlog(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('App_Blog:blog_list')
    template_name = 'App_Blog/delete_blog.html'

# class BlogSearchView(LoginRequiredMixin, ListView):
#     context_object_name = 'blogs'
#     model = Blog
#     template_name = 'App_Blog/search.html'

#     def get_queryset(self) :
#        query = self.request.GET.get('q')
#        queryset = Blog.objects.filter(blog_title__icontains=query).order_by('-blog_title')
class BlogSearchView(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/search.html'

    def get_queryset(self):
        query = self.request.GET.get('q')

        if query:
            # Lọc bài đăng theo tiêu đề chứa từ khóa tìm kiếm
            queryset = Blog.objects.filter(blog_title__icontains=query).order_by('-blog_title')
        else:
            # Nếu không có từ khóa tìm kiếm, trả về tất cả các bài đăng
            queryset = Blog.objects.all()

        # Sắp xếp kết quả theo thời gian xuất bản giảm dần
        return queryset.order_by('-publish_date')
    
class MostLikedBlogView(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/most_liked_blog.html'

    def get_queryset(self):
        # Truy vấn để lấy bài blog có số lượt thích nhiều nhất
        most_liked_blog = Blog.objects.annotate(num_likes=Count('liked_blog')).order_by('-num_likes').first()
        return [most_liked_blog]
    
class MostCommentedBlogView(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/most_commented_blog.html'

    def get_queryset(self):
        # Truy vấn để lấy bài blog có số lượng comment nhiều nhất
        most_commented_blog = Blog.objects.annotate(num_comments=Count('blog_comment')).order_by('-num_comments').first()
        return [most_commented_blog]
class UploadVideo(LoginRequiredMixin, CreateView):
    model = Video
    template_name = 'App_Blog/upload_video.html'
    fields = ('caption', 'video',)

    def form_valid(self, form):
        video = form.save(commit=False)
        caption=video.caption
        video.save()
        return HttpResponseRedirect(reverse('index'))

class UploadList(ListView):
    context_object_name = 'videos'
    model = Video
    template_name = 'App_Blog/upload_list.html'  

# class DeleteVideo(LoginRequiredMixin,View) :
#     context_object_name = 'videos'
#     model = Video
#     template_name = 'App_Blog/upload_list.html'  

#     def delete_video(request, video_id):
#     # Lấy video dựa trên video_id
#         video = Video.objects.get(id=video_id)
#     # Xóa video
#         video.delete()
#     # Chuyển hướng người   dùng đến trang chính sau khi xóa
#         return redirect('home')

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}
<div class="row">
  <div class="col-sm-6">
    <h2>{{blog.blog_title}}</h2>
    <h4>Posted By: @{{blog.author}}</h4>
    <i><h6>Published On: {{blog.publish_date}}</h6></i>
    <i><h6>Updated On: {{blog.update_date}}</h6></i>
    <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
  </div>
  <div class="col-sm-6">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>
  <p>
    {{blog.blog_content|linebreaks}}
  </p>
  <hr>

  </div>
  {% if not liked %}
  <a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
  </a>
  {% else %}
  <a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
  </a>
  {% endif %}
  <div class="row">
    <div class="col-sm-6">
      <hr>
      <h5>Comments:</h5>
      {% for comment in blog.blog_comment.all %}
      <p><a href="#">@{{comment.user}}</a> {{comment.comment}}<br><h6>{{comment.comment_date}}</h6></p>
      {% endfor %}
    </div>
    <div class="col-sm-6">
      <form method="POST">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Comment</button>
      </form>
    </div>

  </div>
  <br>
  <br>

  {% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block body_block %}

<div style="width: 20%; float:right">
  <div class="">
    <div class="card card_cate_blog_default">
      <form action="{% url 'App_Blog:most_liked_blog' %}" method="get">
        <button type="submit"> Bài Viết Có Nhiều Lượt Like Nhất </button>

      </form>
    </div>
  </div>
    <div class="">
     <div class ="card card_cate_blog_default">
   <form action="{% url 'App_Blog:most_commented_blog' %}" method="get">  
    <button type = "submit"> Bài Viết Có Nhiều Lượt Comment Nhất </button> 
   </form>
     </div>
   </div>
</div>
<div style="width: 100%; float:left">

  <div style="width: 100%; float:left">
    {% for blog in blogs %}

    <h3>{{blog.blog_title}}</h3>
    <h6><i>{{blog.publish_date}}</i></h6>
    <div class="row">
      <div class="col-sm-4">
        <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
      </div>
      <div class="col-sm-4">
        <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read
            More</a></p>
        <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count }} Comments </h6>
      </div>
    </div>
    <hr>

    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
  {% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {% endblock %}
{% block body_block %}
<h2>Write Your Blog Here:</h2>
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>
{% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/delete_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}
{% if blog.author == user %}

<div class="row">
  <div class="col-sm-6">
    <h2>{{blog.blog_title}}</h2>
    <h4>Posted By: @{{blog.author}}</h4>
    <i><h6>Published On: {{blog.publish_date}}</h6></i>
    <i><h6>Updated On: {{blog.update_date}}</h6></i>
    <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
  </div>
  <div class="col-sm-6">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>
  <p>
    {{blog.blog_content|linebreaks}}
  </p>
  <hr>

  </div>
  {% if not liked %}
  <a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
  </a>
  {% else %}
  <a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
  </a>
  {% endif %}
  <div class="row">
    <div class="col-sm-6">
      <hr>
      <h5>Comments:</h5>
      {% for comment in blog.blog_comment.all %}
      <p><a href="#">@{{comment.user}}</a> {{comment.comment}}<br><h6>{{comment.comment_date}}</h6></p>
      {% endfor %}
    </div>
    <div class="col-sm-6">
      <form method="POST">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Comment</button>
      </form>
    </div>

  </div>
  <br>
  <br>
  
<form method="POST" id="delete-form">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="button" id="delete-btn">Delete</button>
</form>
<script>
document.addEventListener('DOMContentLoaded', function() {
  document.getElementById('delete-btn').addEventListener('click', function() {
    if (confirm('Are you sure you want to delete this blog post?')) {
      document.getElementById('delete-form').submit();
    }
  });
});
</script>
{% else %}
<p>Your are not allowed to view this page. 404</p>
{% endif %}
{% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/delete_video.html
<!-- {% extends 'base.html' %} 
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block body_block %}
<h2>Video:</h2>
{% for video in videos %}
<div class="container">
    <h3 class="text-center mt-2 mb-2">{{video.caption}}</h3>
        <video class="embed-responsive embed-responsive-16by9" controls="controls" >
            <source src="/media/{{video.video}}" type="video/mp4" />
        </video>
    {% endfor %}
</div>
<hr> 
{% endblock %} 
 -->

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}
{% if blog.author == user %}
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" name="button">Update</button>
{% else %}
<p>Your are not allowed to view this page. 404</p>
</form>
{% endif %}
{% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/most_blogs_username.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users with Most Blogs</title>
</head>
<body>
    <h1>Users with Most Blogs</h1>
    <ul>
        {% for user in users %}
            <li>
                <h2>{{ user.username }}</h2>
                <p>Number of Blogs: {{ user.num_blogs }}</p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/most_commented_blog.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block body_block %}
<!-- Liked 
 <div style="width: 20%; float:right">
  <div class="">
    <div class ="card card_cate_blog_default">
  <form action="{% url 'App_Blog:most_liked_blog' %}" method="get"> 
    <button type = "submit"> Bài Viết Có Nhiều Lượt Liked Nhất </button>
    
  </form>
    </div>
  </div>
</div>
<div style="width: 80%; float:left"> 



  <div style="width: 20%; float:right">
     <div class="">
      <div class ="card card_cate_blog_default">
    <form action="{% url 'App_Blog:most_commented_blog' %}" method="get">  
     <button type = "submit"> Bài Viết Có Nhiều Lượt Comment Nhất </button> 
    </form>
      </div>
    </div>
  </div>
  <div style="width: 80%; float:left">  -->
  {% for blog in blogs %}

  <h3>{{blog.blog_title}}</h3> 
  <h6><i>{{blog.publish_date}}</i></h6>
  <div class="row">
    <div class="col-sm-4">
      <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
    </div>
      <div class="col-sm-4">
        <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a></p>
        <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count }} Comments </h6>
      </div>
    </div>
  <hr>
  {% endfor %}
</div>


{% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/most_liked_blog.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block body_block %}
<!-- Liked 
 <div style="width: 20%; float:right">
  <div class="">
    <div class ="card card_cate_blog_default">
  <form action="{% url 'App_Blog:most_liked_blog' %}" method="get"> 
    <button type = "submit"> Bài Viết Có Nhiều Lượt Liked Nhất </button>
    
  </form>
    </div>
  </div>
</div>
<div style="width: 80%; float:left"> 



  <div style="width: 20%; float:right">
     <div class="">
      <div class ="card card_cate_blog_default">
    <form action="{% url 'App_Blog:most_commented_blog' %}" method="get">  
     <button type = "submit"> Bài Viết Có Nhiều Lượt Comment Nhất </button> 
    </form>
      </div>
    </div>
  </div>
  <div style="width: 80%; float:left">  -->
  {% for blog in blogs %}

  <h3>{{blog.blog_title}}</h3> 
  <h6><i>{{blog.publish_date}}</i></h6>
  <div class="row">
    <div class="col-sm-4">
      <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
    </div>
      <div class="col-sm-4">
        <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a></p>
        <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count }} Comments </h6>
      </div>
    </div>
  <hr>
  {% endfor %}
</div>


{% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} {{user}} {% endblock %}
{% block body_block %}
{% for blog in user.post_author.all %}
<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}}</p>
    <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>
  </div>
</div>
<a href="{% url 'App_Blog:edit_blog' pk=blog.pk %}">Edit</a>
<a href="{% url 'App_Blog:delete_blog' pk=blog.pk %}">Delete</a>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('delete-btn').addEventListener('click', function() {
      if (confirm('Are you sure you want to delete this blog post?')) {
        document.getElementById('delete-form').submit();
      }
    });
  });
  </script>
<hr>
{% endfor %}
{% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/search.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block body_block %}
{% for blog in blogs %}
<h3>{{blog.blog_title}}</h3>
<h6><i>{{blog.publish_date}}</i></h6>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a></p>
    <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
    <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count }} Comments </h6>
  </div>
</div>
<hr>
{% endfor %}
{% endblock %}

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/upload_list.html
 {% extends 'base.html' %} 
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block body_block %}
<h2>Video:</h2>

{% for video in videos %}

<div class="container">
    <h3 class="text-center mt-2 mb-2">{{video.caption}}</h3>
        <video class="embed-responsive embed-responsive-16by9" controls="controls" >
            <source src="/media/{{video.video}}" type="video/mp4" />
        </video>
    {% endfor %}
</div>
<hr> 

{% endblock %} 

Developing-a-Blog-Website-with-Django-main/bog_webite_django/templates/App_Blog/upload_video.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {% endblock %}
{% block body_block %}
<h2>Upload Your Video Here:</h2>
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>
{% endblock %}